### ISSUE TITLE
Manual Azure App Deploy does not guarantee all files are deployed

### ISSUE THREAD

**Issue by dperez3** [im-practices/.github#127]
## Problem
🚨 The zip step before deploying a web app can [silently omit/ignore files](https://linux.die.net/man/1/zip#:~:text=If%20zip%20is,how%20many%20skipped.) - resulting in runtime errors after deployment.

### Ex
https://github.com/im-funding/funding-election/runs/5118922421?check_suite_focus=true#step:9:28

![image](https://user-images.githubusercontent.com/7634621/153260377-2819ac67-b741-428a-89e9-7ad38bb341e1.png)

### Area of concern...
- [Unzipping the Release](https://github.com/im-practices/.github/blob/31168132df09ada497b8907c6a2c1538efd0d2bf/workflow-templates/im-deploy-az-app-manually.yml#L217-L220)
- [Zipping for Deploy](https://github.com/im-practices/.github/blob/31168132df09ada497b8907c6a2c1538efd0d2bf/workflow-templates/im-deploy-az-app-manually.yml#L260-L263)

```
Workflow Code: AmbitiousLizard_v23
```

## Suggestions
I don't yet know for sure why it was unable to zip these files, but I suspect it has to do the `chmod` permissions command in the "Unzip" step not working as expected. Perhaps the "Zip" command still doesn't have permission to those files.

In either case...

1. I think the zip command should have the [`--must-match` flag added](https://linux.die.net/man/1/zip#:~:text=%2DMM-,%2D%2Dmust%2Dmatch,-All%20input%20patterns). If I understand it correctly, this will cause the script to fail if it can't zip all the expected deployment files.
2. Unzip's `chmod` command may need to be fixed (not sure if this was the first failure). It should also fail the script, if it wasn't able to grant permissions to all files (again, not sure if that is already the case).
3. I've personally removed the `-qq` flag from the Unzip step to help diagnose this issue.

## ➡➡➡  Update - This Fixed My Issue ⬅⬅⬅

I actually fixed the missing files and got my deployment working by making an [update to the Build Workflow](https://github.com/im-practices/.github/blob/31168132df09ada497b8907c6a2c1538efd0d2bf/workflow-templates/im-build-dotnet-ci.yml#L392-L397).

### Fix
➡ The update is to essentially zip the initial Release with linux/ubuntu instead of Powershell. Because the downstream handling of that zip file is done via linux/ubuntu.

https://github.com/im-funding/funding-election/pull/155/commits/811948168d527dff0175d8f3308d26aeb28e7e8e

Without getting into the details, there are differences in how windows and linux handles zip files. Namely, file encodings.

It looks like the template uses pwsh to zip because I guess at one time, the env was Windows. It is Ubuntu now, but this seems to have been missed.

**Comment by dperez3** [comment]
## Update
I actually fixed the missing files and got my deployment to making an [update to the Build Workflow](https://github.com/im-practices/.github/blob/31168132df09ada497b8907c6a2c1538efd0d2bf/workflow-templates/im-build-dotnet-ci.yml#L392-L397).

➡ The update is to essentially zip the initial Release with linux/ubuntu instead of Powershell. Because the downstream handling of that zip file is done via linux/ubuntu.

Without getting into the details, there are differences in how windows and linux handles zip files. Namely, file encodings.

It looks like the template uses pwsh to zip because I guess at one time, the env was Windows. It is Ubuntu now, but this seems to have been missed.

**Comment by mike-schenk** [comment]
The problem was that `unzip` tries to re-apply the file "mode" that it expects `zip` to have stored in a special place in the archive. When `zip` was not used to create the archive, `unzip` finds `0` in that special place and dutifully sets the extracted file modes to `0`. So, in a nutshell `zip` and `unzip` were not really good cross-platform choices.

We're now handling the cross-platform issue by always using PowerShell (`pwsh` shell) to [`Compress-Archive`](https://github.com/im-practices/.github/blob/main/workflow-templates/im-build-dotnet-ci.yml#L412) and [`Expand-Archive`](https://github.com/im-practices/.github/blob/main/workflow-templates/im-deploy-az-app-manually.yml#L204). This works for release assets and deployments regardless of which OS is used to create the .zip and which one extracts it. The side-effect is that file modes are set to defaults when extracted to Linux filesystems, but that should be fine for our purposes.
